apiVersion: batch/v1
kind: Job
metadata:
  name: yy
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nautilus.optiputer.net/yol070/research-containers/research-login-v2
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        volumeMounts:
        - name: yy-volume
          mountPath: /yy-volume
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
            nvidia.com/gpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
      restartPolicy: Never
      volumes:
        - name: yy-volume
          persistentVolumeClaim:
            claimName: yy-volume
  backoffLimit: 5
